#############################################################################
# Makefile for building draw
# Generated by tmake at 11:53, 2004/09/06
#     Project: draw
#    Template: app.t
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -finline -Winline -g -DDEBUG -DHEAVY_MODELS
CXXFLAGS=	-pipe -finline -Winline -LANG:std -g -DDEBUG -DHEAVY_MODELS
INCPATH	=	-I./bezier -I./aabb -I/usr/X11R6/include
LINK	=	g++
LFLAGS	=	-LANG:std
LIBS	=	$(SUBLIBS) -L/usr/X11R6/lib -lglut -lglui -lGLU -lGL -lXmu -lXext -lX11 -lm
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	
SOURCES =	draw.cc \
		interface.cc \
		models_cc/greek_rev_house.cc \
		models_cc/babe_bw.cc \
		models_cc/heart0.cc \
		models_cc/woody.cc \
		models_cc/she_model.cc \
		drawing.cc \
		texture.cc \
		stroke3D.cc \
		stroke2D.cc \
		input.cc \
		opengl_utils.cc \
		texload.c \
		widgets.c
OBJECTS =	draw.o \
		interface.o \
		models_cc/greek_rev_house.o \
		models_cc/babe_bw.o \
		models_cc/heart0.o \
		models_cc/woody.o \
		models_cc/she_model.o \
		drawing.o \
		texture.o \
		stroke3D.o \
		stroke2D.o \
		input.o \
		opengl_utils.o \
		texload.o \
		widgets.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	draw
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: makefile

makefile: draw.pro
	tmake draw.pro -o makefile

dist:
	$(TAR) draw.tar draw.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) draw.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f core.*

####### Sub-libraries


###### Combined headers


####### Compile

draw.o: draw.cc \
		input.h \
		vec3.h \
		numerics.h \
		opengl_utils.h \
		point.h \
		vec2.h \
		drawing.h \
		trackball.h \
		quat.h \
		stroke3D.h \
		stroke2D.h \
		bezier.h \
		texture.h \
		texload.h \
		interface.h \
		display_lists.h \
		widgets.h

interface.o: interface.cc \
		interface.h \
		texload.h

models_cc/greek_rev_house.o: models_cc/greek_rev_house.cc \
		display_lists.h \
		widgets.h

models_cc/babe_bw.o: models_cc/babe_bw.cc \
		display_lists.h \
		widgets.h

models_cc/heart0.o: models_cc/heart0.cc \
		display_lists.h \
		widgets.h

models_cc/woody.o: models_cc/woody.cc \
		display_lists.h \
		widgets.h

models_cc/she_model.o: models_cc/she_model.cc \
		display_lists.h \
		widgets.h

drawing.o: drawing.cc \
		drawing.h \
		trackball.h \
		quat.h \
		vec3.h \
		numerics.h \
		stroke3D.h \
		opengl_utils.h \
		stroke2D.h \
		input.h \
		point.h \
		vec2.h \
		bezier.h \
		texture.h \
		texload.h

texture.o: texture.cc \
		texture.h \
		texload.h \
		vec2.h \
		numerics.h

stroke3D.o: stroke3D.cc \
		stroke3D.h \
		opengl_utils.h \
		vec3.h \
		numerics.h \
		stroke2D.h \
		input.h \
		point.h \
		vec2.h \
		bezier.h

stroke2D.o: stroke2D.cc \
		stroke2D.h \
		input.h \
		vec3.h \
		numerics.h \
		opengl_utils.h \
		point.h \
		vec2.h \
		bezier.h

input.o: input.cc \
		input.h \
		vec3.h \
		numerics.h \
		opengl_utils.h \
		point.h \
		vec2.h

opengl_utils.o: opengl_utils.cc \
		opengl_utils.h \
		vec3.h \
		numerics.h

texload.o: texload.c \
		texload.h

widgets.o: widgets.c \
		widgets.h

